# Generated by Django 4.2.1 on 2023-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentarios',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tituloC',
            field=models.CharField(max_length=200, verbose_name='titulo comentario'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(verbose_name='descripcion videojuego'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='link',
            field=models.TextField(verbose_name='link tienda'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='trailer',
            field=models.TextField(verbose_name='trailer videojuego'),
        ),
    ]
